
package xcos_part1;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Pooja M S
 */
public class PopupWindow extends javax.swing.JFrame {
    private JButton submit;
    private JLabel submitLabel;
    private JLabel changeBkgLabel;
    private JLabel changeForeLabel;
    private JLabel changeTextLabel;
    private JPanel panel;
    private JTextField changeBkg;
    private JTextField changeFore;
    private JTextField changeText;
    private PopupBox changeProps;
    private Color foreColor;
    private Color bkgColor;
    /**
     * Creates new form PopupWindow
     */
    public PopupWindow(PopupBox popup) {
        initialize();
        this.changeProps = popup;
        initComponents();
    }
    
    private void initialize()
    {
        
        submit = new JButton();
        submitLabel = new JLabel();
        changeBkgLabel = new JLabel();
        changeForeLabel = new JLabel();
        changeTextLabel = new JLabel();
        panel = new JPanel();
        changeBkg = new JTextField();
       // changeBkg.setBounds(10,10,100,30);
        changeFore = new JTextField();
        changeText = new JTextField();
        this.setTitle("Set Values");
        this.setSize(1000,1000);
        panel.setLayout(new BoxLayout(panel,BoxLayout.Y_AXIS)); 
      
        submitLabel.setText("Change Text");
        changeBkgLabel.setText("Change Background Color");
        changeForeLabel.setText("Change Foreground Color");
        changeTextLabel.setText("Change Text");
   
        submit.setText("Submit");
        
        //Add click event
        submit.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent e) 
            {
                submitClicked(e);
            }
        });
       // panel.add(submitLabel);
        panel.add(changeBkgLabel);
        panel.add(changeBkg);
        panel.add(changeForeLabel);
        panel.add(changeFore);
        panel.add(changeTextLabel);
        panel.add(changeText);
        
        panel.add(submit);
        this.add(panel);
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitClicked(ActionEvent e)
    {
        changeProps.changeLabel(changeText.getText(),changeBkg.getText(),changeFore.getText());
        this.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
