
package xcos_part1;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;

/**
 *
 * @author Pooja M S
 */
public class PopupBox extends javax.swing.JFrame {
    private JPanel panel;
    private JLabel changeProp;   // label to show text
    //Menu items
    private JMenuItem propItem;  
    private JMenuItem dummyItem1;
    private JMenuItem dummyItem2;
    
    //Popup menu to show items
    private JPopupMenu popupMenu;
    private Color foregrdColor;
    private Color backgrdColor;
    private String labelText = null;
    /**
     * Creates new form PopupBox
     */
    public PopupBox() {
        backgrdColor = new Color(255,255,255);
        initialize();
        initComponents();
    }
    private void initialize()
    {
        this.setTitle("Change Properties");
        this.setSize(200,200);
        changeProp = new JLabel();
        propItem = new JMenuItem();
        dummyItem1 = new JMenuItem();
        dummyItem2 = new JMenuItem();
        popupMenu = new JPopupMenu();
                
        dummyItem1.setText("...");
        popupMenu.add(dummyItem1);

        dummyItem2.setText("...");
        popupMenu.add(dummyItem2);

        changeProp.setText("Change Properties");
        changeProp.setFont(new Font("Comic Sans MS", 0, 14));
        changeProp.setOpaque(true);
        
        //Add right click event
        changeProp.addMouseListener(new MouseAdapter() 
        {
            public void mouseReleased(MouseEvent e) 
            {
                if(e.isPopupTrigger())
                    displayPopupMenu(e);
            }
        });
        
        propItem.setText("Properties");
        popupMenu.add(propItem);
        
        //Add click event
        propItem.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent evt) 
            {
                displayPopupWindow(evt);
            }
        });
        
        
        this.add(changeProp);
       // this.add(popupMenu);
        this.setVisible(true);
    }        
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void displayPopupWindow(ActionEvent e)
    {
        new PopupWindow(this);
    }
    private void displayPopupMenu(MouseEvent e)
    {
        popupMenu.show(e.getComponent(), e.getX(), e.getY());
    }
    public void changeLabel(String text, String bg, String fc) //function that is called when submit button is clicked from PopupWindow class.
    {	
    	if (text.length()>0)
        {
            labelText = text;
            changeProp.setText(labelText);
        }
    	if(bg.length()>0)
        {
            backgrdColor = Color.decode(bg);
            changeProp.setBackground(backgrdColor);
        }
    	if(fc.length()>0)
        {
            foregrdColor = Color.decode(fc);
            changeProp.setForeground(foregrdColor);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
